# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend:
    runs-on: [ self-hosted ]
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  frontend:
    env: 
      CI: false
    runs-on: [ self-hosted ]
    defaults:
      run:
        working-directory: hermes
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: hermes/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
